# Generated by Django 4.1.7 on 2023-05-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.IntegerField(null=True)),
                ('merchant_order_id', models.IntegerField()),
                ('order_time', models.DateTimeField()),
                ('payment_time', models.DateTimeField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('stamp', models.CharField(max_length=255)),
                ('to_account', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RefundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_time', models.CharField(max_length=255)),
                ('payment_id', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('balance', models.IntegerField(null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
